export const events = [
    {
        title: "Next.js Conf 2026",
        image: "/images/event1.png",
        slug: "nextjs-conf-2026",
        location: "San Francisco, CA",
        date: "October 24, 2026",
        time: "09:00 AM",
    },
    {
        title: "React Summit",
        image: "/images/event2.png",
        slug: "react-summit-2026",
        location: "Amsterdam, Netherlands",
        date: "June 12, 2026",
        time: "10:00 AM",
    },
    {
        title: "Web Directions Summit",
        image: "/images/event3.png",
        slug: "web-directions-summit-2026",
        location: "Sydney, Australia",
        date: "November 15, 2026",
        time: "09:30 AM",
    },
    {
        title: "JSWorld Conference",
        image: "/images/event4.png",
        slug: "jsworld-conference-2026",
        location: "Online",
        date: "February 25, 2026",
        time: "02:00 PM",
    },
    {
        title: "Node Congress",
        image: "/images/event5.png",
        slug: "node-congress-2026",
        location: "Berlin, Germany",
        date: "April 18, 2026",
        time: "08:00 AM",
    },
    {
        title: "Vue.js Amsterdam",
        image: "/images/event6.png",
        slug: "vuejs-amsterdam-2026",
        location: "Amsterdam, Netherlands",
        date: "March 10, 2026",
        time: "09:00 AM",
    },
];
